package task.web.app.news.entity;
// Generated Aug 9, 2020 4:28:20 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UsersEntity generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="news_app"
    , uniqueConstraints = @UniqueConstraint(columnNames="username") 
)
public class UsersEntity  implements java.io.Serializable {


     private Integer id;
     @JsonBackReference
     private RolesEntity roles;
     private String username;
     private String password;
    @JsonManagedReference
     private Set<NewsEntity> newses = new HashSet<NewsEntity>(0);

    public UsersEntity() {
    }

	
    public UsersEntity(RolesEntity roles, String username, String password) {
        this.roles = roles;
        this.username = username;
        this.password = password;
    }
    public UsersEntity(RolesEntity roles, String username, String password, Set<NewsEntity> newses) {
       this.roles = roles;
       this.username = username;
       this.password = password;
       this.newses = newses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="roles_id", nullable=false)
    public RolesEntity getRoles() {
        return this.roles;
    }
    
    public void setRoles(RolesEntity roles) {
        this.roles = roles;
    }

    
    @Column(name="username", unique=true, nullable=false, length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set<NewsEntity> getNewses() {
        return this.newses;
    }
    
    public void setNewses(Set<NewsEntity> newses) {
        this.newses = newses;
    }




}


